/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package disquera.gui;


import java.awt.Dimension; 
import java.awt.Toolkit;

/**
 *
 * @author Jairo
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePrincipal.class.getName());

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuDisco = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAgregarDisco = new javax.swing.JMenuItem();
        jMenuItemModificarDisco = new javax.swing.JMenuItem();
        jMenuItemEliminarDisco = new javax.swing.JMenuItem();
        jMenuItemListarDisco = new javax.swing.JMenuItem();
        jMenuItemBuscarDisco = new javax.swing.JMenuItem();
        jMenuCancion = new javax.swing.JMenu();
        jMenuItemAgregarCancion = new javax.swing.JMenuItem();
        jMenuItemModificarCancion = new javax.swing.JMenuItem();
        jMenuItemEliminarCancion = new javax.swing.JMenuItem();
        jMenuItemListarCanciones = new javax.swing.JMenuItem();
        jMenuItemBuscarCancion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenuDisco.setText("Editar");
        jMenuDisco.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuDiscoMenuSelected(evt);
            }
        });

        jMenu3.setText("Disco");

        jMenuItemAgregarDisco.setText("Agregar");
        jMenuItemAgregarDisco.addActionListener(this::jMenuItemAgregarDiscoActionPerformed);
        jMenu3.add(jMenuItemAgregarDisco);

        jMenuItemModificarDisco.setText("Modificar");
        jMenuItemModificarDisco.addActionListener(this::jMenuItemModificarDiscoActionPerformed);
        jMenu3.add(jMenuItemModificarDisco);

        jMenuItemEliminarDisco.setText("Eliminar");
        jMenuItemEliminarDisco.addActionListener(this::jMenuItemEliminarDiscoActionPerformed);
        jMenu3.add(jMenuItemEliminarDisco);

        jMenuItemListarDisco.setText("Listar");
        jMenuItemListarDisco.addActionListener(this::jMenuItemListarDiscoActionPerformed);
        jMenu3.add(jMenuItemListarDisco);

        jMenuItemBuscarDisco.setText("Buscar");
        jMenuItemBuscarDisco.addActionListener(this::jMenuItemBuscarDiscoActionPerformed);
        jMenu3.add(jMenuItemBuscarDisco);

        jMenuDisco.add(jMenu3);

        jMenuCancion.setText("Cancion");

        jMenuItemAgregarCancion.setText("Agregar");
        jMenuItemAgregarCancion.addActionListener(this::jMenuItemAgregarCancionActionPerformed);
        jMenuCancion.add(jMenuItemAgregarCancion);

        jMenuItemModificarCancion.setText("Modificar");
        jMenuItemModificarCancion.addActionListener(this::jMenuItemModificarCancionActionPerformed);
        jMenuCancion.add(jMenuItemModificarCancion);

        jMenuItemEliminarCancion.setText("Eliminar");
        jMenuItemEliminarCancion.addActionListener(this::jMenuItemEliminarCancionActionPerformed);
        jMenuCancion.add(jMenuItemEliminarCancion);

        jMenuItemListarCanciones.setText("Listar");
        jMenuItemListarCanciones.addActionListener(this::jMenuItemListarCancionesActionPerformed);
        jMenuCancion.add(jMenuItemListarCanciones);

        jMenuItemBuscarCancion.setText("Buscar");
        jMenuItemBuscarCancion.addActionListener(this::jMenuItemBuscarCancionActionPerformed);
        jMenuCancion.add(jMenuItemBuscarCancion);

        jMenuDisco.add(jMenuCancion);

        jMenuBar1.add(jMenuDisco);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAgregarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarDiscoActionPerformed
        FrmIngresoDisco frm = new FrmIngresoDisco();
        
        frm.setLocationRelativeTo(null); 
        frm.setVisible(true);          
        
    }//GEN-LAST:event_jMenuItemAgregarDiscoActionPerformed

    private void jMenuItemModificarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarCancionActionPerformed
        new FrmModificarCancion().setLocationRelativeTo(null); 
        new FrmModificarCancion().setVisible(true);
    }//GEN-LAST:event_jMenuItemModificarCancionActionPerformed

    private void jMenuDiscoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuDiscoMenuSelected

    }//GEN-LAST:event_jMenuDiscoMenuSelected

    private void jMenuItemModificarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarDiscoActionPerformed
        new FrmModificarDisco().setLocationRelativeTo(null); 
        new FrmModificarDisco().setVisible(true);
    }//GEN-LAST:event_jMenuItemModificarDiscoActionPerformed

    private void jMenuItemEliminarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarDiscoActionPerformed
        new FrmEliminarDisco().setLocationRelativeTo(null); 
        new FrmEliminarDisco().setVisible(true);
    }//GEN-LAST:event_jMenuItemEliminarDiscoActionPerformed

    private void jMenuItemListarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarDiscoActionPerformed
        new FrmListarDiscos().setLocationRelativeTo(null); 
        new FrmListarDiscos().setVisible(true);
    }//GEN-LAST:event_jMenuItemListarDiscoActionPerformed

    private void jMenuItemBuscarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarDiscoActionPerformed
        new FrmBuscarDisco().setLocationRelativeTo(null); 
        new FrmBuscarDisco().setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarDiscoActionPerformed

    private void jMenuItemAgregarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarCancionActionPerformed
        new FrmIngresoCancion().setLocationRelativeTo(null); 
        new FrmIngresoCancion().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarCancionActionPerformed

    private void jMenuItemEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarCancionActionPerformed
        new FrmEliminarCancion().setLocationRelativeTo(null); 
        new FrmEliminarCancion().setVisible(true);
    }//GEN-LAST:event_jMenuItemEliminarCancionActionPerformed

    private void jMenuItemListarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarCancionesActionPerformed
        new FrmListarCanciones().setLocationRelativeTo(null); 
        new FrmListarCanciones().setVisible(true);
    }//GEN-LAST:event_jMenuItemListarCancionesActionPerformed

    private void jMenuItemBuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarCancionActionPerformed
        new FrmBuscarCancion().setLocationRelativeTo(null); 
        new FrmBuscarCancion().setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancion;
    private javax.swing.JMenu jMenuDisco;
    private javax.swing.JMenuItem jMenuItemAgregarCancion;
    private javax.swing.JMenuItem jMenuItemAgregarDisco;
    private javax.swing.JMenuItem jMenuItemBuscarCancion;
    private javax.swing.JMenuItem jMenuItemBuscarDisco;
    private javax.swing.JMenuItem jMenuItemEliminarCancion;
    private javax.swing.JMenuItem jMenuItemEliminarDisco;
    private javax.swing.JMenuItem jMenuItemListarCanciones;
    private javax.swing.JMenuItem jMenuItemListarDisco;
    private javax.swing.JMenuItem jMenuItemModificarCancion;
    private javax.swing.JMenuItem jMenuItemModificarDisco;
    // End of variables declaration//GEN-END:variables
}
